@startuml
title ページ遷移図
login:ログインページ
top:トップページ
list : ユーザ一覧
del:GET 削除確認\nPOST 削除
update:GET 更新確認\nPOST 更新
insert:追加
detail:会員詳細
find:検索

[*]->login
login->top
top-->list:リンク
top-->find:リンク
list-->del:リンク\nid
list-->insert
list-->detail:リンク\nid
del-->del:POST\nid
find-->detail:リンク\nid or name or date
detail-->del:リンク\nid

update-->update:POST\nid\nname\nage\nmail\npass
detail->update:リンク\nid

@enduml