@startuml
left to right direction
rectangle 会員管理システム{
package 画面{
	class ログインページ{

	}
	class トップページ{

	}
	class ユーザ一覧ページ{

	}
	class 検索ページ{

	}
	class 削除ページ{

	}
	class 新規登録ページ{

	}
	class 更新確認ページ{

	}
	class ユーザ詳細ページ{

	}
	class ログアウト{

	}


}

package データベース{
	class ユーザデータ操作{
		+追加(新規登録)
		+削除(会員退会)
		+検索(ユーザID)
		+検索(名前)
		+検索(ふりがな)
		+検索(日付)
		+全検索()
	}
	class ユーザデータ{
		-名前
		-性別
		-年齢
		-メールアドレス
		-保有ポイント
		-パスワード
		-会員クラス
	}
	class 管理者データ{
		-管理者名
		-パスワード
	}
	class 管理者データ操作{

		+検索(管理者ID)

	}
	class 日付データ{
		-ユーザID
		-入館日

	}
	class 会員クラスデータ{
		-クラスID
		-会員分類

	}

}


ログインページ ..> 管理者データ操作

ユーザ一覧ページ ..> ユーザデータ操作
新規登録ページ ..> ユーザデータ操作
更新確認ページ ..> ユーザデータ操作
削除ページ ..> ユーザデータ操作
検索ページ ..> ユーザデータ操作
ユーザ詳細ページ ..>ユーザデータ操作
ユーザデータ操作 *--  ユーザデータ
管理者データ操作 *--  管理者データ
ユーザデータ *-- 日付データ
ユーザデータ *-- 会員クラスデータ

}
@enduml