@startuml
package 画面{
	class ログインページ
	class トップページ
	class ユーザ一覧
	class 検索ページ
	class 削除
	class 新規登録
	class 更新
}
package データベース{
	class データ操作{
		+追加(新規登録)
		+削除(会員退会)
		+検索(ユーザID)
		+検索(名前)
		+検索(日付)
		+全検索()
	}
	class ユーザデータ{
		-名前
		-性別
		-年齢
		-メールアドレス
		-保有ポイント
		-パスワード
		-会員クラス
	}
	class 管理者データ{
		-管理者名
		-パスワード
	}
}

ログインページ --> トップページ
ログインページ ..> 管理者データ
トップページ --> ユーザ一覧
トップページ --> 検索ページ
ユーザ一覧 --> 新規登録
ユーザ一覧 --> 更新
ユーザ一覧 --> 削除
ユーザ一覧 ..> データ操作
新規登録 ..> データ操作
更新 ..> データ操作
削除 ..> データ操作
検索ページ ..> データ操作

データ操作 *--  ユーザデータ
@enduml