@startuml
package 画面{
	class ログインページ{
		+ログイン()
		-パスワード
		-管理者ネーム
	}
	class トップページ{
		+リンク(ユーザ一覧)
		+リンク(検索ページ)
	}
	class ユーザ一覧{
		+リンク(削除)
		+リンク(新規登録)
		+リンク(更新)
	}
	class 検索ページ{
		-ユーザID
		-名前
		-日付
		+検索(ユーザID)
		+検索(名前)
		+検索(日付)
	}
	class 削除{
		+削除()
	}
	class 新規登録{
		+新規登録()
	}
	class 更新{
		+更新()
	}
}
package データベース{
	class ユーザデータ操作{
		+追加(新規登録)
		+削除(会員退会)
		+検索(ユーザID)
		+検索(名前)
		+検索(日付)
		+全検索()
	}
	class ユーザデータ{
		-名前
		-性別
		-年齢
		-メールアドレス
		-保有ポイント
		-パスワード
		-会員クラス
	}
	class 管理者データ{
		-管理者名
		-パスワード
	}
	class 管理者データ操作{
		+追加(管理者追加)
		+削除(管理者削除)
		+検索(管理者ID)
		+全検索()
	}
}

ログインページ --> トップページ
ログインページ ..> 管理者データ操作
トップページ --> ユーザ一覧
トップページ --> 検索ページ
ユーザ一覧 --> 新規登録
ユーザ一覧 --> 更新
ユーザ一覧 --> 削除
ユーザ一覧 ..> ユーザデータ操作
新規登録 ..> ユーザデータ操作
更新 ..> ユーザデータ操作
削除 ..> ユーザデータ操作
検索ページ ..> ユーザデータ操作

ユーザデータ操作 *--  ユーザデータ
管理者データ操作 *--  管理者データ

@enduml