@startuml
title 会員の削除

autonumber "#."

actor 管理者
participant 会員一覧画面
participant 削除画面
database 会員DB
participant 会員

ユーザ -[#green]> 会員一覧画面:削除ボタン
会員一覧画面 -[#blue]> 削除画面:遷移
削除画面 -> 会員DB:データ検索
会員DB -> 会員:生成
会員DB --> 削除画面:会員
削除画面 --[#green]> ユーザ:確認画面
ユーザ -[#green]> 削除画面:削除ボタン
削除画面 -> 会員DB:削除
削除画面 -[#blue]> 会員一覧画面:遷移
会員一覧画面 --[#green]> 管理者:表示
@enduml