@startuml
title 会員の更新

autonumber "#."

actor 管理者
participant 会員詳細画面
participant 更新確認画面
database 会員DB


管理者 -[#green]> 会員詳細画面:会員ボタン
会員詳細画面 -[#green]> 更新確認画面:更新ボタン
更新確認画面 --[#green]> 管理者:確認
更新確認画面 -> 会員DB:データ更新
更新確認画面 -[#blue]> 会員詳細画面:遷移
会員詳細画面 --[#green]> 管理者:表示
@enduml