@startuml
title 会員の削除

autonumber "#."

actor 管理者
participant 会員一覧画面
participant 詳細画面
database 会員DB
participant 会員

管理者 -[#green]> 会員一覧画面:会員ネームをクリック
会員一覧画面 -[#blue]> 詳細画面:遷移
詳細画面 -> 会員DB:データ検索
会員DB -> 会員:生成
会員DB --> 詳細画面:会員
詳細画面 --[#green]> 管理者:ユーザ詳細

@enduml