@startuml

title ログアウト

autonumber "#."

actor 管理者
participant ログインページ
participant ヘッダーログアウト
participant ログインセッション

管理者 -[#green]> ヘッダーログアウト:ログアウトボタンを押す
ヘッダーログアウト --[#green]> 管理者:ログアウト確認の表示
管理者 -[#green]> ログインセッション:ログアウト「はい」を押す
ログインセッション-[#red]> ログインセッション:セッションを取り消す
ログインセッション-[#blue]> ログインページ:遷移
ログインページ -[#green]> 管理者:表示
@enduml