@startuml
actor 管理者
left to right direction
rectangle ユーザ管理{
	管理者 --> (ユーザ検索)
	管理者 --> (ユーザ詳細確認)
	管理者 --> (ユーザ一覧表示)
	管理者 --> (ユーザ削除)
	管理者 --> (ユーザ登録)
	管理者 --> (ユーザ情報更新)

}
管理者 --> (ログイン)
@enduml