@startuml
left to right direction
rectangle 会員管理システム{
package 画面{
	class Login{
		+doPost()
	}
	class Top{
		+doGet()
	}
	class List{
		oGet()
	}
	class Find{
		doGet()
		doPost()
	}
	class Delete{
		doGet()
		doPost()
	}
	class Insert{
		doGet()
		doPost()
	}
	class Update{
		doGet()
		doPost()
	}
	class Detail{
		doGet()
	}
	class Logout{
		doGet()
	}


}

package データベース{
	class UserDAO{
		+insert(User user):void
		+delete(int uid):void
		+update(User user):void
		+fyndByUid(int uid):User
		+findUser(String name,String ruby,Timestamp time):ArryList<User>
	}
	class User{
		-name:String
		-gender:int
		-birthday:Timestamp
		-mail:String
		-point:int
		-password:String
		-class:int
	}
	class Admin{
		-adminId:String
		-password:String
	}
	class AdminDAO{

		+login(String user,String password):void

	}
	class TimeTable{
		-uid:int
		-time:timestamp

	}
	class Gender{
		-gid:int
		-gender:String

	}
	class Userclass{
		-cid:int
		-class:String

	}

}


Login ..> AdminDAO

List ..> UserDAO
Insert ..> UserDAO
Update ..> UserDAO
Delete ..> UserDAO
Find ..> UserDAO
Detail ..>UserDAO
UserDAO *--  User
AdminDAO *--  Admin
User *-- TimeTable
User *-- Userclass
User *-- Gender

}
@enduml