@startuml
title ユーザの検索

autonumber "#."

actor 管理者
participant FindServlet
participant find.jsp

participant UserDAO
database User


管理者 -> FindServlet:Getリクエスト
FindServlet -> find.jsp:フォワード
find.jsp --> 管理者:表示
管理者 -> FindServlet:Postリクエスト
FindServlet -> UserDAO**:new UserDAO()
FindServlet -> UserDAO++:findUser()
UserDAO -> User**:リストを生成
UserDAO -> FindServlet--:Userリスト
FindServlet -> Request++:setAttribute(Userリスト)
FindServlet -> list.jsp:フォワード
Request--
list.jsp --> 管理者:表示


@enduml