@startuml
title ユーザの検索

autonumber "#."

actor 管理者
participant findServlet


database UserDAO
participant User


管理者 -[#green]> findServlet:Getリクエスト
findServlet -> UserDAO**:new UserDAO()
findServlet -> UserDAO++:findUser
UserDAO -> User**:リストを生成
UserDAO -> findServlet--:Userリスト
findServlet -> Request++:setAttribute(Userリスト)
Request--
findServlet -> list.jsp:フォワード
list.jsp --> 管理者:表示


@enduml