@startuml
title ユーザの一覧表示

autonumber "#."

actor 管理者
participant top
participant list
participant UserDAO
database UserDB

管理者->top:doGet
top->list:doGet
list->UserDAO:new UserDAO()
UserDAO->UserDB:ArrayList<User> 生成
UserDAO-->list:doGet
list-->管理者:管理者

@enduml