@startuml
title UpdateServlet

autonumber "#."

actor admin
participant detail
participant UpdateServlet
participant UserDAO
database ユーザDB


admin -> UpdateServlet:doGET
UpdateServlet --> admin:確認画面表示
admin ->UpdateServlet:doPOST
UpdateServlet -> UserDAO:new UserDAO()
UserDAO -> ユーザDB:UpdateServlet()

UpdateServlet -> detail:リダイレクト
detail --> admin:表示
@enduml