@startuml

title LogoutServlet

autonumber "#."

actor 管理者
participant LogoutServlet

participant session
管理者 -> LogoutServlet:doGET
LogoutServlet-> session:removeAttribute
LogoutServlet->login:リダイレクト
login--> 管理者:表示


@enduml