@startuml
title ユーザの更新確認

autonumber "#."

actor admin
participant detail
participant update
database ユーザDB


admin -> detail:情報入力
admin -> detail:更新ボタン
detail -> update:リダイレクト
update --> admin:確認画面表示
admin ->update:更新ボタンをクリック
update -> ユーザDB:データ更新
update -> detail:リダイレクト
detail --> admin:表示
@enduml