@startuml
title ユーザの詳細

autonumber "#."

actor 管理者
participant Detail
participant UserDAO
participant detail.jsp
database User


管理者 -[#green]> Detail:GETリクエスト
Detail -> UserDAO :UserDAO生成
Detail -> UserDAO :findByUid()
UserDAO -> User:リスト生成
UserDAO --> Detail:ユーザリスト
Detail -> detail.jsp:setAttribute(Userリスト)
Detail -> detail.jsp:フォワード
detail.jsp --[#green]> 管理者:ユーザ詳細表示


@enduml