@startuml

title ログイン

autonumber "#."

actor 管理者
participant LoginServlet
participant login.jsp
participant AdminDAO
database Admin

管理者 -> LoginServlet:doGet()
LoginServlet -> login.jsp:フォワード
login.jsp --> 管理者:表示
管理者 -> LoginServlet:doPost()
LoginServlet -> AdminDAO:new AdminDAO()
LoginServlet -> AdminDAO:login()
AdminDAO -> Admin:リスト照合
AdminDAO --> LoginServlet:管理人データ
LoginServlet -> top:リダイレクト
top --> 管理者:表示



@enduml