@startuml
title ユーザの検索

autonumber "#."

actor 管理者
participant findServlet
participant find.jsp

participant UserDAO
database User


管理者 -> findServlet:Getリクエスト
findServlet -> find.jsp:フォワード
find.jsp --> 管理者:表示
管理者 -> findServlet:Postリクエスト
findServlet -> UserDAO**:new UserDAO()
findServlet -> UserDAO++:findUser()
UserDAO -> User**:リストを生成
UserDAO -> findServlet--:Userリスト
findServlet -> Request++:setAttribute(Userリスト)

Request--
findServlet -> list:リダイレクト
list --> 管理者:表示


@enduml