@startuml
title 会員削除
autonumber "#."
actor 管理者
database User

管理者 -[#green]> List.jsp:削除リンククリック
List.jsp ->DelServlet:GETリクエスト
DelServlet -> del.jsp:フォワード
del.jsp --[#green]> 管理者:確認画面表示
管理者 -[#green]> del.jsp:削除ボタンクリック
del.jsp -> DelServlet:POST
DelServlet -> UserDAO:UserDAO生成
DelServlet -> UserDAO:削除
UserDAO -> User:delete()
del.jsp-[#blue]> List.jsp:リダイレクト
List.jsp --[#green]> 管理者:表示
database User
@enduml