@startuml

title LogoutServlet

autonumber "#."

actor admin
participant LogoutServlet

participant session
admin -> LogoutServlet:doGET
LogoutServlet-> session:removeAttribute
LogoutServlet->login:リダイレクト
login--> admin:表示


@enduml