@startuml
title 会員削除
autonumber "#."
actor 管理者
database User


管理者 ->DelServlet:GETリクエスト
DelServlet -> delete.jsp:フォワード
delete.jsp --> 管理者:確認画面表示
管理者 -> DelServlet:POSTリクエスト

DelServlet -> UserDAO:UserDAO生成
DelServlet -> UserDAO:delete()
UserDAO -> User:削除
DelServlet-> list:リダイレクト
list --> 管理者:表示

database User
@enduml