@startuml

title logout

autonumber "#."

actor admin
participant logout

participant session
admin -> logout:doGET
logout-> session:removeAttribute
logout->login:doGET
login--> admin:表示


@enduml