@startuml
title ユーザの追加

autonumber "#."

actor 管理者
participant insertServlet
participant insert.jsp
participant UserDAO
database User


管理者 -> insertServlet:Getリクエスト
insertServlet -> insert.jsp:フォワード
insert.jsp --> 管理者:表示
管理者 -> insertServlet:Postリクエスト
insertServlet -> UserDAO**:new UserDAO()
insertServlet -> UserDAO++:new User()
UserDAO -> User**:insert()
UserDAO--
insertServlet -> list:リダイレクト
list --> 管理者:表示

@enduml