@startuml
title ユーザの追加

autonumber "#."

actor 管理者
participant insertServlet
participant insert.jsp
database UserDAO
participant User


管理者 -> insertServlet:Getリクエスト
insertServlet -> insert.jsp:フォワード
insert.jsp --> 管理者:表示
管理者 -> insertServlet:Postリクエスト
insertServlet -> UserDAO**:new UserDAO()
insertServlet -> UserDAO++:Userデータ
UserDAO -> User**:データベースに追加
UserDAO--
insertServlet -> find:リダイレクト
find --> 管理者:表示

@enduml